export const buildAchievementGameStats = ({
  statsSnapshot,
  gameState,
  trackedMaxLength
}) => ({
  ...statsSnapshot,
  games: statsSnapshot.totalGames || 0,
  wins: statsSnapshot.totalWins || 0,
  totalScore: statsSnapshot.totalScore || 0,
  bestScore: statsSnapshot.bestScore || 0,
  singleScore: gameState.score,
  maxSpeed: statsSnapshot.maxSpeed || 1,
  foodEaten: statsSnapshot.foodEaten || 0,
  singleGameFood: gameState.foodEaten,
  maxLength: Math.max(statsSnapshot.maxLength || 1, trackedMaxLength),
  moves: statsSnapshot.moves || 0,
  totalPlayTime: statsSnapshot.totalPlayTime || 0,
  closeCalls: statsSnapshot.closeCalls || 0,
  fastEats: statsSnapshot.fastEats || 0,
  bonusFoodsCollected: statsSnapshot.bonusFoodsCollected || 0,
  bonusFoodPoints: statsSnapshot.bonusFoodPoints || 0,
  survivalTime: Math.max(0, Math.floor(gameState.gameTime)),
  maxSurvivalTime: statsSnapshot.maxSurvivalTime || 0,
  winStreak: statsSnapshot.currentWinStreak || 0,
  bestWinStreak: statsSnapshot.bestWinStreak || 0,
  wallHits: statsSnapshot.wallHits || 0,
  selfHits: statsSnapshot.selfHits || 0,
  quickDeaths: statsSnapshot.quickDeaths || 0,
  aiWins: (statsSnapshot.aiEasyWins || 0) + (statsSnapshot.aiMediumWins || 0) + (statsSnapshot.aiImpossibleWins || 0),
  aiEasyWins: statsSnapshot.aiEasyWins || 0,
  aiMediumWins: statsSnapshot.aiMediumWins || 0,
  aiImpossibleWins: statsSnapshot.aiImpossibleWins || 0,
  aiImpossibleStreak: statsSnapshot.aiImpossibleStreak || 0,
  multiplayerGames: statsSnapshot.multiplayerGames || 0,
  multiplayerWins: statsSnapshot.multiplayerWins || 0,
  multiplayerGames4Player: statsSnapshot.multiplayerGames4Player || 0,
  multiplayerWins4Player: statsSnapshot.multiplayerWins4Player || 0,
  multiplayerWins4PlayerAllAbove50: statsSnapshot.multiplayerWins4PlayerAllAbove50 || 0,
  playerCount: gameState.playerCount || 1,
  friendsCount: statsSnapshot.friendsCount || 0,
  difficulty: gameState.difficulty || null,
  leaderboardTop100Finishes: statsSnapshot.leaderboardTop100Finishes || 0,
  leaderboardTop10Finishes: statsSnapshot.leaderboardTop10Finishes || 0,
  leaderboardTop3Finishes: statsSnapshot.leaderboardTop3Finishes || 0,
  leaderboardRank1Finishes: statsSnapshot.leaderboardRank1Finishes || 0,
  achievementLeaderboardTop10Finishes: statsSnapshot.achievementLeaderboardTop10Finishes || 0,
  overallLeaderboardTop10Finishes: statsSnapshot.overallLeaderboardTop10Finishes || 0,
  leaderboardTop3BestWeekStreak: statsSnapshot.leaderboardTop3BestWeekStreak || 0,
  weeklyLeaderboardTop100Finishes: statsSnapshot.weeklyLeaderboardTop100Finishes || 0,
  weeklyLeaderboardTop10Finishes: statsSnapshot.weeklyLeaderboardTop10Finishes || 0,
  weeklyLeaderboardTop3Finishes: statsSnapshot.weeklyLeaderboardTop3Finishes || 0,
  weeklyLeaderboardRank1Finishes: statsSnapshot.weeklyLeaderboardRank1Finishes || 0,
  weeklyOverallTop10Finishes: statsSnapshot.weeklyOverallTop10Finishes || 0,
  weeklyTop3BestWeekStreak: statsSnapshot.weeklyTop3BestWeekStreak || 0,
  transparentScore: statsSnapshot.transparentScore || 0,
  perfectGame: (gameState.wallHits || 0) === 0 && (gameState.selfHits || 0) === 0 && gameState.score > 0
});
