import { getIconComponent } from '../../utils/iconMap.js';

export const buildGamePageControllerViewModel = ({
  boardSize,
  deadPlayers,
  food,
  foodEaten,
  gameStatus,
  gameTime,
  getCurrentKeyMappings,
  getInputPerformance,
  handleContinue,
  handleLeaveCancel,
  handleLeaveConfirm,
  handleQuit,
  handleRestart,
  handleShareScore,
  handleTouchControl,
  highlightCollision,
  inputWarning,
  isGameActive,
  isGameOver,
  isMultiplayerMode,
  isPaused,
  isVictory,
  leaveConfirmState,
  loading,
  mobile,
  multiplayerReadyPlayers,
  newAchievement,
  numPlayers,
  onTouchEnd,
  onTouchMove,
  onTouchStart,
  resolvedDifficulty,
  resolvedMode,
  resolvedSessionState,
  score,
  setShowAchievementModal,
  setShowGameOverModal,
  showAchievementModal,
  showCollisionHighlight,
  showGameOverModal,
  showPerformanceMonitor,
  snakes,
  speedMultiplier,
  togglePause
}) => {
  const AchievementIcon = newAchievement ? getIconComponent(newAchievement.icon) : null;

  return {
    AchievementIcon,
    aiFinalScore: resolvedSessionState.aiFinalScore,
    boardSize,
    deadPlayers,
    food,
    foodEaten,
    gameStatus,
    gameTime,
    getCurrentKeyMappings,
    getInputPerformance,
    handleContinue,
    handleLeaveCancel,
    handleLeaveConfirm,
    handleQuit,
    handleRestart,
    handleShareScore,
    handleTouchControl,
    highlightCollision,
    inputWarning,
    isGameActive,
    isGameOver,
    isMultiplayerMode,
    isPaused,
    isVictory,
    isVsAiMode: resolvedSessionState.isVsAiMode,
    leaveConfirmState,
    loading,
    mobile,
    modalTitle: resolvedSessionState.modalTitle,
    multiplayerReadyPlayers,
    multiplayerScoreRows: resolvedSessionState.multiplayerScoreRows,
    multiplayerWinner: resolvedSessionState.multiplayerWinner,
    newAchievement,
    numPlayers,
    onTouchEnd,
    onTouchMove,
    onTouchStart,
    readyPlayersCount: resolvedSessionState.readyPlayersCount,
    resolvedDifficulty,
    resolvedMode,
    score,
    setShowAchievementModal,
    setShowGameOverModal,
    showAchievementModal,
    showCollisionHighlight,
    showGameOverModal,
    showPerformanceMonitor,
    snakes,
    speedMultiplier,
    togglePause,
    userFinalScore: resolvedSessionState.userFinalScore,
    vsAiResultLabel: resolvedSessionState.vsAiResultLabel
  };
};
